mutation UpdateNotification($allowedSection: [NotificationsSection!]) {
  customerProfileUpdate(input: { notificationsSettings: { allowedSections: $allowedSection } }) {
    user {
      id
    }
  }
}
